name: Complex Numbers Operations Test

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./src
    
    strategy:
      matrix:
        python-version: [3.8, 3.9, 3.11]
        
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      
      - name: Test Code
        run: | 
          python ./test_real.py
          python ./test_imag.py
          python ./test_complex.py